# Generated by Django 2.2.1 on 2019-06-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='static/img/team/', verbose_name='Картинка')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Имя и фамилия')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('mail', models.CharField(blank=True, max_length=50, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='TextTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=1000, verbose_name='Текст о сотрудниках')),
            ],
            options={
                'verbose_name': 'Текст о сотрудниках',
                'verbose_name_plural': 'Текст о сотрудниках',
            },
        ),
    ]
