# Generated by Django 2.2.1 on 2019-06-27 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20190621_1531'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Teams',
        ),
    ]
