# Generated by Django 2.2.1 on 2019-07-05 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20190627_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='img/team/', verbose_name='Картинка')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Имя и фамилия')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('mail', models.CharField(blank=True, max_length=50, verbose_name='Электронная почта')),
                ('date_add', models.DateField(blank=True, default=datetime.datetime(2019, 7, 5, 13, 23, 19, 805379), verbose_name='Дата добавления')),
                ('date_edit', models.DateField(blank=True, null=True, verbose_name='Дата редактирования')),
                ('date_del', models.DateField(blank=True, null=True, verbose_name='Дата удаления')),
            ],
            options={
                'verbose_name': 'Команда логировании',
                'verbose_name_plural': 'Команды логирование',
            },
        ),
    ]
