# Generated by Django 2.2.1 on 2019-07-05 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_teamslog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamslog',
            name='img',
        ),
        migrations.RemoveField(
            model_name='teamslog',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='teamslog',
            name='name',
        ),
        migrations.RemoveField(
            model_name='teamslog',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='teamslog',
            name='position',
        ),
        migrations.AddField(
            model_name='teamslog',
            name='teams',
            field=models.ManyToManyField(to='team.Teams'),
        ),
        migrations.AlterField(
            model_name='teamslog',
            name='date_add',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 7, 5, 13, 25, 52, 789660), verbose_name='Дата добавления'),
        ),
    ]
