# Generated by Django 2.2.1 on 2019-07-05 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20190705_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamslog',
            name='teams',
        ),
        migrations.AddField(
            model_name='teams',
            name='log',
            field=models.ManyToManyField(to='team.TeamsLog'),
        ),
        migrations.AlterField(
            model_name='teamslog',
            name='date_add',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 7, 5, 13, 27, 10, 254707), verbose_name='Дата добавления'),
        ),
    ]
