# Generated by Django 2.2.1 on 2019-07-05 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_auto_20190705_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='date_add',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 7, 5, 15, 17, 52, 297669), verbose_name='Дата добавления'),
        ),
    ]
