# Generated by Django 2.2.1 on 2019-07-10 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0011_auto_20190710_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='date_add',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 7, 10, 14, 30, 0, 461140), verbose_name='Дата добавления'),
        ),
    ]
