# Generated by Django 2.2.1 on 2019-07-05 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_auto_20190705_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_main',
            name='date_add',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 7, 5, 15, 17, 52, 305667), verbose_name='Дата добавления'),
        ),
        migrations.AddField(
            model_name='admin_main',
            name='date_edit',
            field=models.DateField(blank=True, null=True, verbose_name='Дата редактирования'),
        ),
    ]
