# Generated by Django 2.2.1 on 2019-07-05 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_auto_20190705_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_main',
            name='date_add',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 7, 5, 15, 20, 21, 918841), verbose_name='Дата добавления'),
        ),
    ]
