# Generated by Django 2.2.1 on 2019-06-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=25, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=30, verbose_name='Электронная почта')),
                ('address_fact', models.CharField(blank=True, max_length=250, verbose_name='Адрес')),
                ('vk', models.CharField(blank=True, max_length=150, verbose_name='ВКонтакте')),
                ('insta', models.CharField(blank=True, max_length=150, verbose_name='Инстаграм')),
                ('inn', models.CharField(blank=True, max_length=50, verbose_name='ИНН')),
                ('ogrn', models.CharField(blank=True, max_length=50, verbose_name='ОГРН')),
                ('kpp', models.CharField(blank=True, max_length=50, verbose_name='КПП')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Contact_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=70, verbose_name='Описание страницы')),
                ('desc', models.CharField(blank=True, max_length=250, verbose_name='Описание сайта для поисковых систем')),
                ('keywords', models.CharField(blank=True, max_length=500, verbose_name='Ключевые слова')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактные информации',
            },
        ),
    ]
