# Generated by Django 2.2.1 on 2019-06-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='img',
            field=models.ImageField(blank=True, upload_to='static/img/', verbose_name='Картинка'),
        ),
    ]
