# Generated by Django 2.2.1 on 2019-07-05 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20190703_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='date_add',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 7, 5, 15, 20, 21, 913842), verbose_name='Дата добавления'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='date_edit',
            field=models.DateField(blank=True, null=True, verbose_name='Дата редактирования'),
        ),
    ]
