# Generated by Django 2.2.1 on 2019-06-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_token', models.CharField(blank=True, max_length=250, verbose_name='Токен')),
                ('title', models.CharField(blank=True, max_length=70, verbose_name='Описание страницы')),
                ('desc', models.CharField(blank=True, max_length=250, verbose_name='Описание сайта для поисковых систем')),
                ('keywords', models.CharField(blank=True, max_length=500, verbose_name='Ключевые слова')),
            ],
            options={
                'verbose_name': 'Карта',
                'verbose_name_plural': 'Карты',
            },
        ),
        migrations.CreateModel(
            name='Map_contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ico', models.CharField(blank=True, max_length=25, verbose_name='Иконка')),
                ('text', models.CharField(blank=True, max_length=50, verbose_name='Текст')),
                ('info', models.CharField(blank=True, max_length=100, verbose_name='Описание и значение')),
            ],
            options={
                'verbose_name': 'Контакт Карты',
                'verbose_name_plural': 'Контакт Карт',
            },
        ),
    ]
