# Generated by Django 2.2.1 on 2019-06-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=70, verbose_name='Описание страницы')),
                ('desc', models.CharField(blank=True, max_length=250, verbose_name='Описание сайта для поисковых систем')),
                ('keywords', models.CharField(blank=True, max_length=500, verbose_name='Ключевые слова')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактные информации',
            },
        ),
        migrations.CreateModel(
            name='CompanyNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=70, verbose_name='Описание страницы')),
                ('desc', models.CharField(blank=True, max_length=250, verbose_name='Описание сайта для поисковых систем')),
                ('keywords', models.CharField(blank=True, max_length=500, verbose_name='Ключевые слова')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.RemoveField(
            model_name='company',
            name='ico',
        ),
        migrations.RemoveField(
            model_name='company',
            name='name_romb',
        ),
        migrations.RemoveField(
            model_name='company',
            name='numbers',
        ),
        migrations.RemoveField(
            model_name='company',
            name='text',
        ),
        migrations.AddField(
            model_name='company',
            name='big_text',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='company',
            name='small_text',
            field=models.TextField(blank=True, max_length=500, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='company',
            name='title',
            field=models.CharField(blank=True, max_length=270, verbose_name='Описание страницы'),
        ),
    ]
