# Generated by Django 2.2.1 on 2019-06-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20190618_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='small_text',
            field=models.TextField(blank=True, max_length=500, verbose_name='Маленький текст'),
        ),
    ]
