# Generated by Django 2.2.1 on 2019-07-10 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20190705_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date_add',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 7, 10, 14, 16, 13, 769819), verbose_name='Дата добавления'),
        ),
    ]
