# Generated by Django 2.2.1 on 2019-05-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_romb'),
    ]

    operations = [
        migrations.AddField(
            model_name='romb',
            name='name_romb',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
