# Generated by Django 2.2.1 on 2019-05-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_romb_name_romb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cars', models.CharField(blank=True, max_length=150)),
                ('img', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=25)),
                ('text', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Грузоперевозки',
                'verbose_name_plural': 'Грузоперевозки',
            },
        ),
    ]
