# Generated by Django 2.2.1 on 2019-05-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='img',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='car',
            name='text',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
