# Generated by Django 2.2.1 on 2019-05-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20190531_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_work', models.CharField(blank=True, max_length=150)),
                ('img', models.CharField(blank=True, max_length=150)),
                ('name', models.CharField(blank=True, max_length=25)),
                ('text', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name': 'Грузоперевозки',
                'verbose_name_plural': 'Грузоперевозки',
            },
        ),
    ]
