# Generated by Django 2.2.1 on 2019-05-31 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_work'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'Как мы работаем', 'verbose_name_plural': 'Как мы работаем'},
        ),
    ]
