# Generated by Django 2.2.1 on 2019-05-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20190531_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_part', models.CharField(blank=True, max_length=150)),
                ('img', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
