# Generated by Django 2.2.1 on 2019-05-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='We_pred',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pred', models.CharField(blank=True, max_length=150)),
                ('img', models.CharField(blank=True, max_length=150)),
                ('text', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Мы представляем',
                'verbose_name_plural': 'Мы представляем',
            },
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Партнёр', 'verbose_name_plural': 'Партнёры'},
        ),
    ]
