# Generated by Django 2.2.1 on 2019-06-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20190531_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Описание сайта',
                'verbose_name_plural': 'Описания сайта',
            },
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyw', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Ключевые слова сайта',
                'verbose_name_plural': 'Ключевые слова сайта',
            },
        ),
    ]
