# Generated by Django 2.2.1 on 2019-06-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_description_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, verbose_name='Имя')),
                ('email', models.CharField(blank=True, max_length=500, verbose_name='Электронная почта')),
                ('phone', models.CharField(blank=True, max_length=500, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Завка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, max_length=150, verbose_name='Картинка')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Имя и фамилия')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.AlterField(
            model_name='car',
            name='img',
            field=models.CharField(blank=True, max_length=150, verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(blank=True, max_length=25, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='car',
            name='name_cars',
            field=models.CharField(blank=True, max_length=150, verbose_name='Наименование грузоперевозки'),
        ),
        migrations.AlterField(
            model_name='car',
            name='text',
            field=models.CharField(blank=True, max_length=250, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address_fact',
            field=models.CharField(blank=True, max_length=250, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, max_length=30, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='insta',
            field=models.CharField(blank=True, max_length=150, verbose_name='Инстаграм'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=25, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='vk',
            field=models.CharField(blank=True, max_length=150, verbose_name='ВКонтакте'),
        ),
        migrations.AlterField(
            model_name='description',
            name='desc',
            field=models.CharField(blank=True, max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='keywords',
            name='keyw',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='img',
            field=models.CharField(blank=True, max_length=150, verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name_part',
            field=models.CharField(blank=True, max_length=150, verbose_name='Наименование партнёра'),
        ),
        migrations.AlterField(
            model_name='romb',
            name='ico',
            field=models.CharField(blank=True, max_length=25, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='romb',
            name='name_romb',
            field=models.CharField(blank=True, max_length=150, verbose_name='Наименование ромба'),
        ),
        migrations.AlterField(
            model_name='romb',
            name='numbers',
            field=models.CharField(blank=True, max_length=10, verbose_name='Цифры'),
        ),
        migrations.AlterField(
            model_name='romb',
            name='text',
            field=models.CharField(blank=True, max_length=50, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='we_pred',
            name='img',
            field=models.CharField(blank=True, max_length=150, verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='we_pred',
            name='name_pred',
            field=models.CharField(blank=True, max_length=150, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='we_pred',
            name='text',
            field=models.CharField(blank=True, max_length=150, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='work',
            name='img',
            field=models.CharField(blank=True, max_length=150, verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='work',
            name='name',
            field=models.CharField(blank=True, max_length=25, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='work',
            name='name_work',
            field=models.CharField(blank=True, max_length=150, verbose_name='Наименование работы'),
        ),
        migrations.AlterField(
            model_name='work',
            name='text',
            field=models.CharField(blank=True, max_length=700, verbose_name='Текст'),
        ),
    ]
