# Generated by Django 2.2.1 on 2019-06-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_auto_20190611_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='img',
            field=models.ImageField(blank=True, upload_to='static/img/partners/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='team',
            name='img',
            field=models.ImageField(blank=True, upload_to='static/img/team/', verbose_name='Картинка'),
        ),
    ]
