# Generated by Django 2.2.1 on 2019-06-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_partner_modal'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_part', models.CharField(blank=True, max_length=150, verbose_name='Наименование партнёра')),
                ('img', models.ImageField(blank=True, upload_to='static/img/partners/', verbose_name='Логотип')),
                ('text', models.CharField(blank=True, max_length=150, verbose_name='Описание партнёра')),
                ('number', models.CharField(blank=True, max_length=150, verbose_name='Номер телефона')),
                ('email', models.CharField(blank=True, max_length=150, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
            },
        ),
        migrations.RemoveField(
            model_name='partner',
            name='modal',
        ),
    ]
