# Generated by Django 2.2.1 on 2019-06-11 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_auto_20190611_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allpartner',
            options={'verbose_name': 'Все партнёры', 'verbose_name_plural': 'Все партнёры'},
        ),
    ]
