# Generated by Django 2.2.1 on 2019-06-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_auto_20190611_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allpartner',
            name='email',
            field=models.CharField(blank=True, max_length=50, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='allpartner',
            name='number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='allpartner',
            name='text',
            field=models.CharField(blank=True, max_length=650, verbose_name='Описание партнёра'),
        ),
    ]
