# Generated by Django 2.2.1 on 2019-06-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_auto_20190611_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=1000, verbose_name='Текст о сотрудниках')),
            ],
            options={
                'verbose_name': 'Текст о сотрудниках',
                'verbose_name_plural': 'Текст о сотрудниках',
            },
        ),
        migrations.AlterField(
            model_name='allpartner',
            name='img',
            field=models.ImageField(blank=True, upload_to='img/partners/', verbose_name='Логотип'),
        ),
    ]
