# Generated by Django 2.2.1 on 2019-06-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_auto_20190617_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='mail',
            field=models.CharField(blank=True, max_length=50, verbose_name='Электронная почта'),
        ),
    ]
