# Generated by Django 2.2.1 on 2019-06-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_team_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_logo', models.ImageField(blank=True, upload_to='img/', verbose_name='Маленькое лого')),
                ('logo', models.ImageField(blank=True, upload_to='img/', verbose_name='Большое лого')),
                ('background', models.ImageField(blank=True, upload_to='img/', verbose_name='Задний фон картинка')),
            ],
            options={
                'verbose_name': 'Логотип',
                'verbose_name_plural': 'Логотип',
            },
        ),
    ]
