# Generated by Django 2.2.1 on 2019-06-21 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TextTeam',
        ),
    ]
