# Generated by Django 2.2.1 on 2019-06-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0023_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='img',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='Картинка'),
        ),
    ]
