# Generated by Django 2.2.1 on 2019-06-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0026_auto_20190627_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='img',
            field=models.ImageField(blank=True, upload_to='static/img/work/', verbose_name='Картинка'),
        ),
    ]
