# Generated by Django 2.2.1 on 2019-07-05 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0027_auto_20190627_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_add',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 7, 5, 15, 17, 52, 280667), verbose_name='Дата добавления'),
        ),
        migrations.AddField(
            model_name='contact',
            name='date_edit',
            field=models.DateField(blank=True, null=True, verbose_name='Дата редактирования'),
        ),
        migrations.AddField(
            model_name='romb',
            name='date_add',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 7, 5, 15, 17, 52, 281668), verbose_name='Дата добавления'),
        ),
        migrations.AddField(
            model_name='romb',
            name='date_edit',
            field=models.DateField(blank=True, null=True, verbose_name='Дата редактирования'),
        ),
    ]
