# Generated by Django 2.2.1 on 2019-07-05 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0028_auto_20190705_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='allpartner',
            name='date_add',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 7, 5, 15, 20, 21, 899841), verbose_name='Дата добавления'),
        ),
        migrations.AddField(
            model_name='allpartner',
            name='date_edit',
            field=models.DateField(blank=True, null=True, verbose_name='Дата редактирования'),
        ),
        migrations.AddField(
            model_name='car',
            name='date_add',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 7, 5, 15, 20, 21, 897842), verbose_name='Дата добавления'),
        ),
        migrations.AddField(
            model_name='car',
            name='date_edit',
            field=models.DateField(blank=True, null=True, verbose_name='Дата редактирования'),
        ),
        migrations.AddField(
            model_name='logo',
            name='date_add',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 7, 5, 15, 20, 21, 903841), verbose_name='Дата добавления'),
        ),
        migrations.AddField(
            model_name='logo',
            name='date_edit',
            field=models.DateField(blank=True, null=True, verbose_name='Дата редактирования'),
        ),
        migrations.AddField(
            model_name='partner',
            name='date_add',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 7, 5, 15, 20, 21, 899841), verbose_name='Дата добавления'),
        ),
        migrations.AddField(
            model_name='partner',
            name='date_edit',
            field=models.DateField(blank=True, null=True, verbose_name='Дата редактирования'),
        ),
        migrations.AddField(
            model_name='team',
            name='date_add',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 7, 5, 15, 20, 21, 900840), verbose_name='Дата добавления'),
        ),
        migrations.AddField(
            model_name='team',
            name='date_edit',
            field=models.DateField(blank=True, null=True, verbose_name='Дата редактирования'),
        ),
        migrations.AddField(
            model_name='we_pred',
            name='date_add',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 7, 5, 15, 20, 21, 901842), verbose_name='Дата добавления'),
        ),
        migrations.AddField(
            model_name='we_pred',
            name='date_edit',
            field=models.DateField(blank=True, null=True, verbose_name='Дата редактирования'),
        ),
        migrations.AddField(
            model_name='work',
            name='date_add',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 7, 5, 15, 20, 21, 898842), verbose_name='Дата добавления'),
        ),
        migrations.AddField(
            model_name='work',
            name='date_edit',
            field=models.DateField(blank=True, null=True, verbose_name='Дата редактирования'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_add',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 7, 5, 15, 20, 21, 896842), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='romb',
            name='date_add',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 7, 5, 15, 20, 21, 897842), verbose_name='Дата добавления'),
        ),
    ]
