# Generated by Django 2.2.1 on 2019-07-10 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0029_auto_20190705_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.AlterField(
            model_name='allpartner',
            name='date_add',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 7, 10, 14, 16, 13, 711818), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='car',
            name='date_add',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 7, 10, 14, 16, 13, 708818), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_add',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 7, 10, 14, 16, 13, 706818), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='date_add',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 7, 10, 14, 16, 13, 719820), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='date_add',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 7, 10, 14, 16, 13, 710819), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='romb',
            name='date_add',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 7, 10, 14, 16, 13, 707818), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='team',
            name='date_add',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 7, 10, 14, 16, 13, 711818), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='we_pred',
            name='date_add',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 7, 10, 14, 16, 13, 712818), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='work',
            name='date_add',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 7, 10, 14, 16, 13, 709818), verbose_name='Дата добавления'),
        ),
    ]
