# Generated by Django 2.2.1 on 2019-07-10 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0030_auto_20190710_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allpartner',
            name='date_add',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 7, 10, 14, 30, 0, 445138), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='car',
            name='date_add',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 7, 10, 14, 30, 0, 443139), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_add',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 7, 10, 14, 30, 0, 442129), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='date_add',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 7, 10, 14, 30, 0, 449140), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='date_add',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 7, 10, 14, 30, 0, 445138), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='romb',
            name='date_add',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 7, 10, 14, 30, 0, 443139), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='team',
            name='date_add',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 7, 10, 14, 30, 0, 446138), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='we_pred',
            name='date_add',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 7, 10, 14, 30, 0, 447138), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='work',
            name='date_add',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 7, 10, 14, 30, 0, 444138), verbose_name='Дата добавления'),
        ),
    ]
