from django.urls import path, include
from adminpanel.views import *

urlpatterns = [
    path('panel/', board, name='board'),
    path('panel/<int:pk>/', board_del, name='board_del'),
    path('panel/edit/<int:pk>/', board_edit, name='board_edit'),
    path('panel/contact/', dashboard, name='dashboard'),
    path('panel/contact/<int:pk>/', dashboard_del, name='dashboard_del'),
    path('panel/page_index/', page_index, name='page_index'),
    path('panel/page_index/<int:pk>/', page_index_del, name='page_index_del'),
    path('panel/page_index/edit/<int:pk>/', page_index_edit, name='page_index_edit'),
    path('panel/logo/', logo, name='logo'),
    path('panel/logo/<int:pk>/', logo_del, name='logo_del'),
    path('panel/gruz/', gruz, name='gruz'),
    path('panel/gruz/<int:pk>/', gruz_del, name='gruz_del'),
    path('panel/gruz/edit/<int:pk>/', gruz_edit, name='gruz_edit'),
    path('panel/work/', work, name='work'),
    path('panel/work/<int:pk>/', work_del, name='work_del'),
    path('panel/work/edit/<int:pk>/', work_edit, name='work_edits'),
    path('panel/part/', part, name='part'),
    path('panel/part/<int:pk>/', part_del, name='part_del'),
    path('panel/part/edit/<int:pk>/', part_edit, name='part_edit'),
    path('panel/pred/', pred, name='pred'),
    path('panel/pred/<int:pk>/', pred_del, name='pred_del'),
    path('panel/pred/edit/<int:pk>/', pred_edit, name='pred_edit'),
    path('panel/team_index/', team_index, name='team_index'),
    path('panel/team_index/<int:pk>/', team_index_del, name='team_index_del'),
    path('panel/team_index_edit/<int:pk>/', team_index_edit, name='team_index_edit'),
    path('panel/partners/', partners, name='partners'),
    path('panel/partners/<int:pk>/', partners_del, name='partners_del'),
    path('panel/partners/edit/<int:pk>/', partners_edit, name='partner_edit'),
    path('panel/teams/', teams, name='teams'),
    path('panel/teams/<int:pk>/', teams_del, name='teams_del'),
    path('panel/teams/edit/<int:pk>/', teams_edit, name='team_edit'),
    path('panel/company/', company, name='company'),
    path('panel/company/<int:pk>/', company_del, name='company_del'),
    path('panel/contacts/', contacts, name='contacts'),
    path('panel/contacts/<int:pk>/', contacts_del, name='contacts_del'),
    path('panel/settings/', settings, name='settings'),
]
